create or replace view DB_RETAIL.STG.VIEW_PRODUCT(
	PRODUCT_ID,
	PRODUCT_LENGTH,
	PRODUCT_DEPTH,
	PRODUCT_WIDTH,
	CLUSTER_ID,
	HIERARCHY1_ID,
	HIERARCHY2_ID,
	HIERARCHY3_ID,
	HIERARCHY4_ID,
	HIERARCHY5_ID
) as select * from DB_RETAIL.STG.PRODUCT_HIERARCHY;