create or replace view DB_RETAIL.STG.VIEW_SALES(
	PRODUCT_ID,
	STORE_ID,
	DATE,
	SALES,
	REVENUE,
	STOCK,
	PRICE,
	PROMO_TYPE_1,
	PROMO_BIN_1,
	PROMO_TYPE_2,
	PROMO_BIN_2,
	PROMO_DISCOUNT_2,
	PROMO_DISCOUNT_TYPE_2
) as ( select * from  DB_RETAIL.STG.SALES);